
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ecomerce_backend:latest
    container_name: ecomerce_backend
    build: ./backend
    ports:
      - "8000:8000" 
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
